"""add rank

Revision ID: b9a1651c034c
Revises: 1fbcfcadd947
Create Date: 2019-07-17 11:44:31.415751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a1651c034c'
down_revision = '1fbcfcadd947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snack', sa.Column('rank', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('snack', 'rank')
    # ### end Alembic commands ###
